### ISSUE TITLE
why does restarting the container also rewrite all the config to default 

### ISSUE THREAD

**Issue by achiragaming** [LsHallo/ets2-dedicated-convoy-server#29] opened 2024-10-06 16:36 UTC

**Comment by LsHallo** [comment] 2024-10-06 17:10
Please provide a description and steps you've tried.

**Comment by achiragaming** [comment] 2024-10-06 17:16
> Please provide a description and steps you've tried.
# You can freely choose which server to run. They don't depend on one another.
# This file gives an example config for both games.
version: "3.3"
services:
  ets2-server:
    image: lshallo/ets2-convoy-server
    # image: ghcr.io/lshallo/ets2-convoy-server # GitHub container registry
    container_name: ets2-server
    restart: unless-stopped
    tty: true
    network_mode: host # important to make game appear in server list
    # if you want to join via direct join token (displayed in logs on startup) you can use port mapping
    # the game will not appear in server list because the server can't determine the external IP
    ports:
      - "27015:27015"
      - "27016:27016"
      - "27015:27015/udp"
      - "27016:27016/udp"
    volumes:
    # Server files. (executable, libraries)
    # Only mount if you know what you are doing. Can lead to permissions issues.
    #   - "/home/ninoko/ets_data/ets2-server2/server_files:/app"
    # Only needed when using custom server_packages.sii and server_packages.dat.
    # Also keeps banlist. If you want to persist the banlist mount this folder.
      - "/home/ninoko/ets_data/ets2-server2/save-data:/home/steam/.local/share/Euro Truck Simulator 2"
    environment:
      - "ETS_SERVER_UPDATE_ON_START=true"
      - "ETS_SERVER_NAME=Achira Gaming Server"
      - "ETS_SERVER_DESCRIPTION=My server description"
      - "ETS_SERVER_WELCOME_MESSAGE=Welcome to my server!"
      - "ETS_SERVER_PASSWORD=achira@22.66.99"
      - "ETS_SERVER_MAX_PLAYERS=8"
      - "ETS_SERVER_PORT=27015"
      - "ETS_SERVER_QUERY_PORT=27016"
      # more variables...



this is my docker-compose.yml file and when i do docker-compose up -d it starts the server and i tried to add a admin user by going to server_config.sii in /home/ninoko/ets_data/ets2-server2/save-data and when i add the admin user and do docker-compose down and docker-compose up -d it all changes to the enviroments that i put on the docker-compose.yml and i even tried by restarting the container but it still writes default values to the config

**Comment by LsHallo** [comment] 2024-10-06 17:19
Yes that's why here are environment variables to set server moderators (admins). Then the environment variables get written into the server config on startup so you don't have to manually edit the config. Every possible option is exposed using environment variables.
So you set `ETS_SERVER_MODERATORS=<your id>,<another id>` and my script will write the moderators to server_config.sii on startup.

**Comment by achiragaming** [comment] 2024-10-06 17:20
> Yes that's why here are environment variables to set server moderators (admins). Then the environment variables get written into the server config on startup so you don't have to manually edit the config. Every possible option is exposed using environment variables. So you set ETS_SERVER_MODERATORS=, and my script will write the moderators to server_config.sii on startup.

also the session id changes in every restart too

**Comment by LsHallo** [comment] 2024-10-06 17:22
If you do not provide a login token that is expected behaviour.

**Comment by achiragaming** [comment] 2024-10-06 17:24
> If you do not provide a login token that is expected behaviour.

oh ohk so is there any docs for dedicated server that i can read because i dont know how to set a login token

**Comment by LsHallo** [comment] 2024-10-06 17:31
Sure. It's included in the repo: https://github.com/LsHallo/ets2-dedicated-convoy-server/blob/master/ETS_SERVER_README.md#7-server-logon-token

**Comment by LsHallo** [comment] 2024-10-12 08:57
Since you haven't reported any more problems in the past 7 days I'm closing this as completed.

**Closed as completed by LsHallo** 2024-10-12 08:57 UTC
